# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08dba648107f370b560c0bd47820b029632af5bfba8848904b90e3595ce426996c20231fc7b5f6956642873315ce1b18a1f1077df860cc1719214885ed6dc1ab

test:
  secret_key_base: 980520ac746347dcfaab1d934981f5794b9e2d3a45cb43baf933abefd3fcb2f44d132562b0eea9fcee17bd73ff744e3bd739a524337b5d2d91585853a92a7bc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
